### ISSUE TITLE
bias_<tracer> is a wrong name in fitter2

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#382]
In fitter2, `bias_i` is actually defined as the following:
![image](https://user-images.githubusercontent.com/3166436/38054875-69584c22-3295-11e8-8fec-ab4a3654ed68.png)
Either we should change the name of this parameter or change the definition in `py/picca/py/fitter2/utils.py:::bias_beta()`.
I have no strong opinions on what is better.
What do you think @ngbusca, @vserret, @mblomqvist?

**Comment by vserret** [comment]
bias_eff_i ?

**Comment by andreufont** [comment]
The problem with "velocity bias" is that it is used in other contexts in sister communities (galaxy clusetring). 

I would call it bias_eta_i , the name that has been used in the past in most Lyman alpha papers, where eta is the (dimensionless) line of sight velocity gradient.

On a related note, I would change the parameter (and not just the name) of the second bias in Lya fits. I would use bias_delta_i as the other parameter, instead of beta_i, unless someone figures out the combination of parameters that are less degenerate.

**Comment by andreufont** [comment]
Another thing that we could do is to have fitter2 to write down also "derived parameters", similar to what CAMB / CLASS do. We can distinguish the parameters that actually go in the fits (and those should be whatever combination is less degenerate) to the parameters that we want to look at and have physical meaning, and in this case we can write 5 different combinations if we wanted.

**Comment by ngbusca** [comment]
The problem is that this should be a parameter name that works for both discrete and absorption tracers. Is bias_eta also used in the galaxy clustering comunity? Same thing for bias_delta, we would have a `bias_delta_QSO` that we would typically fix to 1.

**Comment by andreufont** [comment]
bias_eta and bias_delta are both valid parameters for any tracer. They represent the response of a large scale fluctuation in the tracer with respect to a large scale fluctuation in the density field (bias_delta) or in the velocity gradient (bias_eta). 

For galaxies (or quasars) we have:
 - bias_delta = bias_galaxy
 - bias_eta = 1 (although Hirata 2009 points out that there might be % deviations)

**Comment by ngbusca** [comment]
Thanks @andreufont, it makes sense to me. If there are no objections from @londumas @vserret or @mblomqvist I'll PR the changes (within a week or two, no rush)

**Comment by mblomqvist** [comment]
So the PR would modify the pair combination and names to be bias_eta_i and bias_delta_i? I'm fine with the names. In the current setup, bias_i and beta_i have a parameter correlation of -0.85 for the Lya auto-correlation, but it seems that this won't be improved.

**Comment by mblomqvist** [comment]
Sure, it's the same thing as what I meant, except I thought of it as
bias_X -> bias_eta_X (i.e. only a new name)
beta_X -> bias_delta_X (i.e. change of parameter)

**Comment by andreufont** [comment]
Yes, although I prefer to write it this way :-)

P_tracer(k,mu) = (bias_delta_X + f*bias_eta_X mu**2)**2 P(k)

**Comment by mblomqvist** [comment]
In the object-forest cross-correlation, one would then measure the bias of the object bias_delta_Y (bias_eta_Y would naturally be unity) while also floating the forest bias_eta_X (since forest bias_delta_X is degenerate with object bias_delta_Y). If too degenerate, one would also have to fix bias_eta_X.

**Comment by londumas** [comment]
https://github.com/igmhub/picca/blob/636792ed131afc007f9f698c47ac90a63081037d/py/picca/fitter2/utils.py#L122

Indeed it gives `b*beta / f`

**Comment by londumas** [comment]
Fixed
