### ISSUE TITLE
distance in cf. x_correlation is wrong

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#408]
@vserret, I noticed a mistake in `do_cf.py` and similar correlations at line 188:
```
    elif lambda_abs != lambda_abs2:
        x_correlation=True
        data2  = copy.deepcopy(data)
        ndata2 = copy.deepcopy(ndata)
        dels2 = copy.deepcopy(dels)
```
This is not good since `lambda_abs != lambda_abs2` implies different values for `z` and thus different values for `((1+z)/(1+zref))**(alpha-1)` and more important a wrong `d.r_comov`
Correcting this mistake could be a good opportunity of changing the way we read data in `do_cf.py` and other correlations. Let's read it only using the function in `io.py`.
What do you think? Is this option used a lot?

**Comment by vserret** [comment]
I don't understand your problem since if you have in_dir == in_dir2 and lambda_abs != lambda_abs2, x_correlation = True 
and we take the data2 = data and  dels2 = dels but we use them and we compute z, we and r_comov from l.214 to l.234. 
So the value seem correctly computed in the case of the x correlation, right ?

**Comment by londumas** [comment]
Indeed, l.214 to l.234 do the job. Sorry for the noise.
