### ISSUE TITLE
Debug queue for NERSC script

### ISSUE THREAD

**Issue by andreufont** [igmhub/picca#487]
It would be great if the queue was set to "debug" when using the --debug option for the NERSC script.

**Comment by ngbusca** [comment]
That doesn't work since you can't submit more tha  5 jobs at the same time to the debug queue...

**Comment by andreufont** [comment]
I see. That's unfortunate, but I guess one can modify these by hand if in a hurry.

**Comment by ngbusca** [comment]
I'm opening this issue again since I realized a better way to submit jobs: 
* send `do_delta` as the first job
* group all the `do_cf`, `do_dmat`, ... into a single `.batch` and submit to several nodes
* idem for `export` and `fitter2`
* Splitting on a sufficiently large number of redshift bins could ensure submission to the debug queue, even for full-desi runs.

The `quickquasars` submission script that @julienguy developed uses this trick. See also https://docs.nersc.gov/jobs/examples/#running-multiple-parallel-jobs-simultaneously

**Comment by iprafols** [comment]
This might be a bit obsolete given the bookkeeper by @cramirezpe. Then again, we should either update this script (also to using Perlmutter) or else remove it

**Comment by iprafols** [comment]
The bookkepper apparently not yet public so maybe we can just fix the script
