### ISSUE TITLE
standardization

### ISSUE THREAD

**Issue by londumas** [igmhub/picca#693]
@iprafols, I leave you explain your project to improve picca with more standardization. Let's discuss things here, before doing anything to the code.

**Comment by iprafols** [comment]
A while ago I was checking some possible issues regarding the computation of deltas and the distortion matrix, and I found it very hard to understand the flow of picca. This was mostly due to the fact that the names of variables are not very self-explanatory, and the lack of doctrsings.

After looking at it more carefully and I these are the issues that I found:
- [ ] We don't have the workflow of picca documented anywhere.
- [ ] Lack of docstrings.
- [ ] Variables names are not self-explanatory.
- [ ] Variables with different names refer to the same concept.
- [ ] Variables with the same name refer to different concepts.
- [ ] Class variables are sometimes accessed with self, which makes it hard to distinguish them from instance variables.
- [ ] Some functions are treated as variables which makes it confusing

These are not major issues for the behavior of the code but fixing them would make it easier for new developers to get up to speed with picca. What I am doing is the following:

1. Identify the workflow of picca and document it 
2. Run pylint to the code and fix the problems reported there
3. Analyze the different variables and document their meaning
4. Test that the code output does not change using not only the automatic tests but also running the entire analysis on stripe 82.

I started working on this on my fork of picca. The list of variables I have identified is listed alphabetically [here](https://docs.google.com/spreadsheets/d/1PougvkVWN_H5BubOCOs1ylkS0wnFSyDbOc3cvPEJXoc/edit?usp=sharing). Also I am documenting all the changes I am introducing in an [overleaf document](https://www.overleaf.com/read/bffssqsynbmm). Note that since I am doing this project as part of an undergraduate program on computer science, I have a python expert as an advisor for this project.

**Comment by londumas** [comment]
@iprafols, all of that makes a lot of sens but here is the big issue, we do not have full covarage of the unittest. Some of the codes are not tested with unittest. I tis true that the more important ones are thought. So the first step has to build full caverage through unitest.

**Comment by iprafols** [comment]
I wasn't aware of that. I'll add this to the list of things to do

**Comment by londumas** [comment]
If this is not done we risk to introduce a ot of bugs throught for example misspelling variables.
I think the first thing to do is:
 - write the doc strings, this is pretty safe, since it does not change the code
 - write a proper tutorial, thing I started for desi on the wiki
 - create a web-hook with a package like codacy, that tells when some standard are not respected.
What do you think @iprafols ?

**Comment by iprafols** [comment]
This was my initial approach plan, but I am finding it way easier to understand the code after I'm changing the names of the variables. How about this: 
- I keep making the changes in my fork, and once I have the docstrings ready I can merge just the docstrings to start with this, and once we are satisfied with the tests, then merge the rest.
- I'll look into setting up codacy or something like this
- For the tutorial, maybe we can start with the DR14 hack that @andreufont started in the wiki for the Tucson meeting

**Comment by londumas** [comment]
@iprafols, sounds perfect. Note that codacy is already hooked, but more tests can be added for standardization. Codacy was the first step by Nicolas.

**Comment by iprafols** [comment]
cool, so I'll add to add more tests both in codacy and unittest once I understand the code better

**Comment by iprafols** [comment]
I have finished updating the docstrings and adding comments. I also changed the name of the variables since I found it very difficult to understand what the code was doing. A report on all the changes I made can be found here: http://openaccess.uoc.edu/webapps/o2/bitstream/10609/118127/1/iprafolsTFC0620.pdf

**Comment by ngbusca** [comment]
I think this is a great initiative, thanks a lot @iprafols 

At many instances, picca development was mainly driven by goal-oriented pragmatism and certainly grew "too fast" at times... I'm sure your effort will have a very positive impact on the pacakge.

**Comment by iprafols** [comment]
merged into master
