### ISSUE TITLE
Data loading can easily be parallelised

### ISSUE THREAD

**Issue by jfarr03** [igmhub/picca#760]
When running any picca script which loads in large quantities of data, performance is slow as data is all read in series rather than in parallel. For example, when measuring some correlation functions, the loading of delta files or catalogues can take at least as long as the calculation of the correlation itself. In most cases, the data loading process is trivially parallelisable as it can easily be split into per-HEALPix pixel chunks, and so this seems an easy way to make picca more efficient.

I'm not sure what the best way to implement any parallelisation would be, but I have made a start in the branch [improve_picca_data_loading](https://github.com/igmhub/picca/tree/improve_picca_data_loading). I would stress that this branch is by no means ready for any merging as yet - it seems to work nicely but it would be good to discuss the "best practice" of implementing parallelisation before taking this any further.

**Comment by iprafols** [comment]
I totally agree that this could be parallelized. I think the different reading of data should be treated separately. For the reading of deltas, I think we can go ahead and introduce parallelisation. Since delta files are structured in different healpixs, then I guess the best solution will be to use the same Pool solution used for the computation.

For the reading of raw data to compute the deltas, the new version is advancing quite quickly so we can maybe implement parallelisation there, but it's not clear to me what is the best solution. I guess the different reading modes will need to be parallelised separately, but maybe we can wait to add this in the new version, which is advancing nicely.

**Comment by andreufont** [comment]
@iprafols , @Waelthus - I thought that this branch had been merged a long time ago, but now that I'm playing with the boring mocks I realise that we are still waiting a lot of time reading the deltas without parallelisation. 

Should we find a volunteer to take care of this?

**Comment by andreufont** [comment]
For the record, it takes 10 minutes to read the deltas from a full DESI mock realisation.

**Comment by iprafols** [comment]
Hi @andreufont , yes I think we should ask for a volunteer. If I fail to do so on the next telecon, can you remind me?

**Comment by andreufont** [comment]
@iprafols - the pull request merged only addresses the reading of deltas, but not reading spectra

**Comment by iprafols** [comment]
I guess this was closed automatically with the PR

**Comment by iprafols** [comment]
Reading of spectra is now parallelized for DesiHealpix and DesiSim (see PR #875 ). Not sure it makes sense to parallelize data reading for SdssData, but we should probably implement it for DesiTile before closing this issue

**Comment by iprafols** [comment]
DesiTile reading was parallelized a while ago so I guess we can now close this issue. Do you agree @andreufont ?

**Comment by andreufont** [comment]
If all options to read DESI data (healpix, tiles, sims) are parallelised, then yes, we can close it.
