### ISSUE TITLE
Incompatibility of picca_compute_fvoigt.py with DLA catalogs

### ISSUE THREAD

**Issue by Andrea-MG** [igmhub/picca#762]
Hi everyone,

While running picca_compute_fvoigt.py with a DLA catalog with the format used by the DLA finder team I get ths error (that doesn't appear while running with other catalogs, as I discussed previously with Thomas):

`picca_compute_fvoigt.py --dla-catalog /global/cfs/projectdirs/desi/mocks/lya_forest/develop/london/qq_desi/v9.0_Y1/monthly_delay0_v0/desiY1-0.2-DLA/DLA_cat.fits --drq-catalog /project/projectdirs/desi/users/andreamg/Y1_analysis/desiY1-0.2-DLA/Picca/Catalog/zcat_desi_drq.fits -o /project/projectdirs/desi/users/andreamg/Y1_analysis/desiY1-0.2-DLA/unmasked/Picca/Correlations/Fit/Combined/fvoigt.txt`

`read DLA catalog`
`read DRQ catalog`
`only keep DLAs in DRQ quasars LOS`
`Traceback (most recent call last):`
`  File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/astropy/io/fits/column.py", line 1827, in _get_index`
    `indx = names.index(key.rstrip())`
`ValueError: 'MOCKID' is not in list`
`During handling of the above exception, another exception occurred:`
`Traceback (most recent call last):`
  `File "/global/homes/a/andreamg/Programs/Picca_2020/picca/bin/picca_compute_fvoigt.py", line 262, in <module>
    main()`
  `File "/global/homes/a/andreamg/Programs/Picca_2020/picca/bin/picca_compute_fvoigt.py", line 181, in main
    dla = dla[:][np.in1d(dla['MOCKID'], qso['THING_ID'])]`
  `File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/astropy/io/fits/fitsrec.py", line 485, in __getitem__`
    `return self.field(key)`
  `File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/astropy/io/fits/fitsrec.py", line 680, in field`
    `column = self.columns[key]`
  `File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/astropy/io/fits/column.py", line 1434, in __getitem__`
    `key = _get_index(self.names, key)`
  `File "/global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/conda/lib/python3.6/site-packages/astropy/io/fits/column.py", line 1836, in _get_index`
    `raise KeyError("Key '{}' does not exist.".format(key))`
`KeyError: "Key 'MOCKID' does not exist." `

Alma and I suggest that the addition of a conditional that looks for DESI arguments present, or maybe a `-- mode desi` as other PICCA codes.

Thanks in advance!

**Comment by Waelthus** [comment]
Ok, the immediate issue is that your DLA_CAT contains THING_ID/ Z while the code expects MOCKID/ Z_DLA_RSD, for the CAT from the drq file it expects THING_ID which is available, so that should be ok. So the quick workaround would be either renaming columns or modifying lines 181 and 198 of the script to the different column names.

It would definitely make sense to have a mode setting here, if I see this right there need to be at least 3 modes available: 
1. for things like the Saclay mocks v4.4.3 [see helpline when running the code, this is the only thing currently there]: MOCKID/ Z_DLA_RSD in DLA_CAT, THING_ID in drq
2. for things like current desi mocks [like your example]: THING_ID/ Z in DLA_CAT, THING_ID in drq
3. for future desi mocks/data [proper desi naming]: TARGETID/ Z in DLA_CAT, TARGETID in cat

I guess the format for DESI DLA catalogs is still subject to discussion, not sure if the group ever decided on a final format convention for that one.
