### ISSUE TITLE
Make sure that DLA/BAL Catalogs are supported and work as expected

### ISSUE THREAD

**Issue by Waelthus** [igmhub/picca#815]
For the BAL side there has been work by @LaurEnnesser.
For the DLA side ideally the DLA finder group should try to implement a similar approach to the cats.

We do want to be able to run the full analysis with the everest tag, so this needs to be done before.

**Comment by zoujiaqi99** [comment]
Hi, which column names of the current DLA catalog do I need to change?  What do you mean about 'a similar approach'?

**Comment by Waelthus** [comment]
For the BAL catalog the current idea is to add BAL information to the QSO catalog as additional columns to the main ZCATALOG extension. If that's feasible for DLAs, one could do the same for those to unify the treatment of "contaminants".

The other part is to ensure that whichever catalog format we will use for DLAs, picca needs to be able to read it. I'm not sure this is currently the case, but I haven't looked at your catalogs yet. Are those available on NERSC and accessible for everybody?

@alxogm: Have you (or someone else) looked into the DLA cats from @zoujiaqi99 already?

**Comment by andreufont** [comment]
I agree with @iprafols , we should probably use a different catalog for DLAs than for BALs. 

Thank you @zoujiaqi99 for providing the catalog! Regarding column names in your catalog, this is the current list:              
```
TTYPE1  = 'TARGET_RA'                                                           
TTYPE2  = 'TARGET_DEC'                                                          
TTYPE3  = 'ZQSO    '                                                            
TTYPE4  = 'Z       '                                                            
TTYPE5  = 'TARGETID'                                                            
TTYPE6  = 'S/N     '                                                            
TTYPE7  = 'DLAID   '                                                            
TTYPE8  = 'NHI     '                                                            
TTYPE9  = 'DLA_CONFIDENCE'                                                      
TTYPE10 = 'NHI_STD '                                                            
TTYPE11 = 'ABSORBER_TYPE'                                                       
TTYPE12 = 'QSO without BAL'                                                     
TTYPE13 = 'DLA     '                                                            
TTYPE14 = 'Assoc_DLA'                                                           
TTYPE15 = 'Interesting_flag'                                                    
TTYPE16 = 'Comments'     
```                                                       

Some of these are common with other DESI files (TARGET_RA, TARGET_DEC, TARGETID). These are great. 

The function in Picca that reads DLA positions (read_dlas in io.py) currently expects to find columns names 'Z' and 'NHI', so I think we can leave these as they are for now. 

Regarding the other columns, it would be better if you used a consistent format: avoid spaces in the names, and use only capital letters. For instance, I would use "QSO_WITHOUT_BAL" or "NO_BAL_QSO" in column 12, and I would also rename columns 14 and 15. You might also consider using "SNR" instead of "S/N" to avoid the use of non-standard characters. None of these columns are currently used in Picca, so it is not as important to change their names for now.
