### ISSUE TITLE
question about var_lss in true continuum

### ISSUE THREAD

**Issue by alxogm** [igmhub/picca#970]
The issue I have is that in a noiseless mock I have very different weights for the true continuum with respect to the raw analysis. Resulting in wrong CF for the true continuum... 

Looking at the code, I'm confused as to why the function get_var_lss is redefined here. 
 
https://github.com/igmhub/picca/blob/9d3165bee50124c82bfba46f0d2b3c56cfec13f8/py/picca/delta_extraction/expected_fluxes/true_continuum.py#L488
 
This means that for the weights we don't use the variance passed from the raw statistics file but this one that is computed from the deltas? 

@cramirezpe I think you wrote this piece?

**Comment by cramirezpe** [comment]
The reason why we included this modification is that continuum fitting (the estimation of aq and bq parameters) introduces some smoothing in your measured var_lss. There is also an extra smoothing if your pixel size is different than the raw one.

In order to better compare a "normal" run with a true continuum run, we decided to re-compute var_lss for the true continuum in the way is computed in compute_var_lss.

We could add an option to just skip this re-computation if you need it.

**Comment by alxogm** [comment]
Thanks @cramirezpe, yes maybe having that option is helpful, but I still think there might be an issue, since I would expect weights not to be completely different , and so the CF, specially for noiseless mocks

**Comment by alxogm** [comment]
Hi @cramirezpe , yes they are in NERSC. 
Raw deltas: `/global/cfs/cdirs/desi/users/alxogm/desi/andrea/lyacolore_Andrea2/deltas_raw`
True deltas with Master branch: `/global/cfs/cdirs/desi/users/alxogm/desi/andrea/lyacolore_Andrea1/qq_noiseless/picca_full_original/Deltas`
True deltas with my branch (using var_lss from raw analysis) : `/global/cfs/cdirs/desi/users/alxogm/desi/andrea/lyacolore_Andrea1/qq_noiseless/picca_full/Deltas`


FYI, this analysis is for CIV forest, no LYA, but I don't think there should be an issue with that. You can see in this plot how the deltas are similar, but the weights are very different 
![Screen Shot 2023-01-26 at 11 10 05](https://user-images.githubusercontent.com/14896082/214902279-d4fe6073-2522-497a-82f7-5d7269a97761.png)
![Screen Shot 2023-01-26 at 11 10 49](https://user-images.githubusercontent.com/14896082/214902522-080c4621-bb7f-4ce7-9784-109da3279637.png)

**Comment by cramirezpe** [comment]
Hi again Alma,
I tried to reproduce the issues you are having by running three analyses that are analogous to the ones you have:

1. Raw (identical to your raw, in principle).
2. True on master (identical to your true). Labeled as "true"
3. True on a custom branch where I removed the recomputation of var_lss. To do this, I made only this change in the code, just making the recomputation function do nothing. Labeled as "true no recompute."
<img src="https://user-images.githubusercontent.com/58682644/215075623-299674ea-ae0e-4a6a-b8b8-4fc2691e738b.png" width=50%>

I ran these three analyses on a downsampled version of v9 mocks and then read var_lss from the delta_attributes files. For the stack of weights:
- in the case of true analyses, I read them from delta_attributes. 
- for raw, I just recompute them (the ones in the raw_statistics file are just the sum of counts).

I got the following plot, which looks consistent:
<img src="https://user-images.githubusercontent.com/58682644/215075740-735ed53a-1cd8-4467-abe0-46eac2948797.png" width=50%>
For sigma_lss: if I recompute the variance, it gets lower due to smoothing. If I do not recompute the variance, it stays as the input. For the weights: since it is the sum of weights and there are more pixels at low lambda, we have that feature, but true no-recompute and raw are very similar (I guess the differences come from the small amount of pipeline noise?).

I tried to make the same plot for the analyses you mentioned, I used these attributes files (and raw_statistics for var_lss in the case of mocks):
- True: "/global/cfs/cdirs/desi/users/alxogm/desi/andrea/lyacolore_Andrea1/qq_noiseless/picca_full_original/Deltas/Log/delta_attributes.fits.gz"
- True no-recompute: "/global/cfs/cdirs/desi/users/alxogm/desi/andrea/lyacolore_Andrea1/qq_noiseless/picca_full/Deltas/Log/delta_attributes.fits.gz"
- Raw: "/global/cfs/cdirs/desi/users/alxogm/desi/andrea/lyacolore_Andrea2/delta_raw-stats.fits.gz"

And for the raw weights, I used the deltas under:
- "/global/cfs/cdirs/desi/users/alxogm/desi/andrea/lyacolore_Andrea2/deltas_raw"

<img src="https://user-images.githubusercontent.com/58682644/215076001-96ba4642-df80-417a-835d-9cfedf6912b7.png" width=50%>

But the results look odd, I am not sure if I am selecting the appropriate files.

**Comment by alxogm** [comment]
Thanks @cramirezpe , so it seems  that weights explode in a certain range, I'll try to investigate why.  

Anyways I'll submit a PR that allows to no recompute var_lss, as it makes the comparison to the raw mocks more direct. 

Thanks for your help.
